_target_: pytorch_lightning.Trainer

gpus: -1   # set `1` to train on GPU, `0` to train on CPU only
accelerator: "gpu"

min_epochs: 10
max_epochs: 100
max_steps: -1
log_every_n_steps: 100

limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0

weights_summary: null
progress_bar_refresh_rate: 1
resume_from_checkpoint: ""
fast_dev_run: False
