_target_: src.datamodules.FVRDatamodule
data_dir: /mnt/disk_d/Data/FVUSM/FV-USM-processed
train_batch_size: 32 # n_classes * n_samples
train_batch_sampler_n_classes: 8
train_batch_sampler_n_samples: 4
val_batch_size: 1
test_batch_size: 1
num_workers: 0
pin_memory: False
