_target_: src.datamodules.MRAADatamodule
data_dir: /data/kevinhuang/github/articulated-animation/data/FVUSM_256x256_gif
train_batch_size: 8
val_batch_size: 1
test_batch_size: 1
num_workers: 8
pin_memory: False
