_target_: src.litmodels.FVRLitModel

backbone:
  _target_: src.networks.backbones.resnet18

head:
  _target_: src.networks.heads.NormLinearHead
  input: 512 # BasicConvBlock: 512 BottleneckBlock: 2048
  output: 246 # num_classes for FVUSM dataset

losses:
  cosface:
    _target_: src.core.losses.CosFace
    s: 20.0
    m: 0.2
    verbal: False
    loss_weight: 1.0
  tripletloss:
    _target_: src.core.losses.OnlineTripletLoss
    margin: 0.2
    s: 20.0
    is_distance: True
    loss_weight: 4.0

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0
