_target_: src.litmodels.FVRLitModel

backbone:
  _target_: src.networks.backbones.resnet18
  pretrained: True

head:
  _target_: src.networks.heads.NormLinearHead
  input: 512 # BasicConvBlock: 512 BottleneckBlock: 2048
  output: 246 # num_classes for FVUSM dataset

losses:
  cosface:
    _target_: src.core.losses.CosFace
    s: 20.0
    m: 0.2
    verbal: False
    loss_weight: 1.0
  tripletloss:
    _target_: src.core.losses.OnlineTripletLoss
    margin: 0.2
    s: 20.0
    is_distance: True
    loss_weight: 4.0

optimizer:
  type: SGD
  lr: 0.01
  weight_decay: 0.0

# optimizer:
#   type: Adam
#   lr: !!float 1e-4
#   weight_decay: 0.0
#   betas: [0.9, 0.99]

lr_scheduler:
  type: MultiStepLR
  milestones: [60]
  gamma: 0.1
