_target_: src.litmodels.MRAALitModel

region_predictor:
  _target_: src.networks.mraa.RegionPredictor
  num_regions: 10
  num_channels: 3
  estimate_affine: True
  temperature: 0.1
  block_expansion: 32
  max_features: 1024
  scale_factor: 0.25
  num_blocks: 5
  pca_based: True
  pad: 0
  fast_svd: False

bg_predictor: 
  _target_: src.networks.mraa.BGMotionPredictor
  block_expansion: 32 
  num_channels: 3
  max_features: 1024 
  num_blocks: 5
  bg_type: zero

generator: 
  _target_: src.networks.mraa.Generator
  num_regions: 10
  num_channels: 3
  block_expansion: 64
  max_features: 512
  num_down_blocks: 2
  num_bottleneck_blocks: 6
  skips: True
  revert_axis_swap: True
  pixelwise_flow_predictor_params:
    block_expansion: 64
    max_features: 1024
    num_blocks: 5
    scale_factor: 0.25
    use_deformed_source: True
    use_covar_heatmap: True
    estimate_occlusion_map: True

train_params:
  transform_params: 
    sigma_affine: 0.05
    sigma_tps: 0.005
    points_tps: 5
  loss_weights:
    perceptual: 10 # [10, 10, 10, 10, 10]
    equivariance_shift: 10
    equivariance_affine: 10

# # TODO: Add losses from yaml
# losses:
#   perceptual_loss:
#     _target_: src.core.losses.PerceptualLoss

optimizer:
  type: Adam
  lr: !!float 2e-4
  weight_decay: 0.0
  betas: [0.9, 0.99]

lr_scheduler:
  type: MultiStepLR
  milestones: [60, 90]
  gamma: 0.1
